### ISSUE TITLE
Having a context in view function

### ISSUE THREAD

**Issue by pauldijou** [turboMaCk/glue#15]
Is there a way to pass more arguments to the `view` function?

In order to avoid state duplication, most of my `view` functions are something like `view: Context -> Model -> Html a`, where `Context` is all the infos needed from ancestors (already stored in a higher up state) and `Model` is the actual internal state the TEA component.

Couldn't find a way to achieve that using Glue so far...

**Comment by turboMaCk** [comment]
hi @pauldijou,
yes this is quite common use-case. Which version of Glue are you using? This should be pretty strait forward with version 2.0.0.

**Comment by pauldijou** [comment]
Not using it yet. I like the concept so I was considering if it could fit in our project, so 2.0.0 version is fine.

The blocking point is [view](http://package.elm-lang.org/packages/turboMaCk/glue/2.0.0/Glue#view) with the 2nd argument as `(subModel -> Html a)`. But any workaround would be nice.

**Comment by turboMaCk** [comment]
This was a bit problematic (workaround required) with 1.x.x version (see comments in [old README](https://github.com/turboMaCk/glue/tree/1.1.0#downsides)). 

With 2.0.0 you don't have this problem at all. First, you can simply call `view` function directly. Alternative solution is to use build in [Glue.view](http://package.elm-lang.org/packages/turboMaCk/glue/2.0.0/Glue#view) function which takes `Glue` as the first argument and view function as second (like `Glue.view subModule (SubModule.view config) model`).

In case you're interested some additional info can be found in [this issue](https://github.com/turboMaCk/glue/issues/8)

**Comment by pauldijou** [comment]
Cool ! Thanks for the super quick answer. I will try to use it on our next component then.

**Comment by turboMaCk** [comment]
Sounds good. Let me know if you'll run into some issue or have any idea how to improve anything. Also please be aware that technique this lib is working with is a bit unconventional within Elm community so please be careful🤞
